front_end_super:
    resource: "@FrontEndSuperBundle/Resources/config/routing.yml"
    prefix:   /{_locale}

MyAppUtilisateurBundle:
    resource: "@MyAppUtilisateurBundle/Controller/"
    type:     annotation
    prefix:   /

MyAppApBundle:
    resource: "@MyAppApBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/intranet
    defaults:   { _locale: en }
    requirements:
        _locale: en|fr

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"