<?php

namespace MyApp\ApBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientServiceRepository extends EntityRepository
{

    public function getSumSigneClient($client)
    {
        $qb = $this->createQueryBuilder('a')
            ->select('SUM(a.prix)')
            ->join('a.client', 'p')
            ->join('p.contrat', 'c')
            ->where('p.id LIKE :client')
            ->andWhere("c.contratEstimation LIKE :contrat")
            ->setParameters(array('client'=> $client,'contrat'=>'Contrat'));
        return $qb->getQuery()
            ->getResult();
    }

    public function getCountSigneClient($client)
    {
        $qb = $this->createQueryBuilder('a')
            ->select('COUNT(a.prix)')
            ->join('a.client', 'p')
            ->join('p.contrat', 'c')
            ->where('p.id LIKE :client')
            ->andWhere("c.contratEstimation LIKE :contrat")
            ->setParameters(array('client'=> $client,'contrat'=>'Contrat'));
        return $qb->getQuery()
            ->getResult();
    }
    public function getSumProduitClient($client)
    {
        $qb = $this->createQueryBuilder('a')
            ->select('SUM(a.prix)')
            ->join('a.client', 'p')
            ->join('p.production', 'c')
            ->where('p.id LIKE :client')
            ->andWhere("c.statut LIKE :statut")
            ->setParameters(array('client'=> $client,'statut'=>'Terminé'));
        return $qb->getQuery()
            ->getResult();
    }
    public function getCountProduitClient($client)
    {
        $qb = $this->createQueryBuilder('a')
            ->select('COUNT(a.prix)')
            ->join('a.client', 'p')
            ->join('p.production', 'c')
            ->where('p.id LIKE :client')
            ->andWhere("c.statut LIKE :statut")
            ->setParameters(array('client'=> $client,'statut'=>'Terminé'));
        return $qb->getQuery()
            ->getResult();
    }
}




