<?php

namespace MyApp\ApBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComptabiliteRepository extends EntityRepository
{

public function getSumContratClient($client)
  {
    $qb = $this->createQueryBuilder('a')
                      ->select('SUM(a.montant)')
                      ->join('a.production', 'p')
                      ->join('p.client', 'c')
                      ->where('c.id LIKE :client')
                      ->setParameter('client', $client);
        return $qb->getQuery()
                  ->getResult();
  }
}



