parameters:
#    my_app_ap.example.class: MyApp\ApBundle\Example

services:
#    my_app_ap.example:
#        class: %my_app_ap.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    myapp_locale.locale_listener:
        class: MyApp\ApBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

    myapp_ap.message:
        class: MyApp\ApBundle\TextMessage\Message
        arguments: [@twilio.api]

#services:
#    sdzblog.beta_listener:
#        class: MyApp\ApBundle\Beta\BetaListener
#        arguments: ["2010-08-19"]
#        tags:
#            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
